exclude: (alembic)
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [pre-commit]
        language: system
        entry: uv run black
        types: [python]

      - id: autoflake
        name: autoflake
        stages: [pre-commit]
        language: system
        entry: uv run autoflake -i
        types: [python]
        args:
        - --remove-all-unused-imports
        - --ignore-init-module-imports
        - --remove-duplicate-keys

      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: uv run isort
        types: [python]
