name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - name: Run tests
        run: pipenv run pytest
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPN_HOST_IP }}
          username: ${{ secrets.VPN_USER_NAME }}
          password: ${{ secrets.VPN_USER_NAME }}
          port: ${{ secrets.VPN_PORT }}
          script: ls -al
#      - name: Run command on remote server
#        uses: D3rHase/ssh-command-action@v0.2.2
#        with:
#          host: ${{secrets.SSH_HOST}}
#          user: ${{secrets.SSH_USER}}
#          private_key: ${{secrets.SSH_PRIVATE_KEY}}
#          command: |
#            cd ${{ secrets.PROJECT_FOLDER }};
#            git checkout master;
#            git pull;
#            docker-compose --file docker-compose.prod.yml down;
#            docker-compose --file docker-compose.prod.yml up -d;
#            docker system prune --all --force;