name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: uv pip install flake8
      - run: uv pip install pylint
      - run: uv pip install mypy
      - run: uv run flake8
      - run: uv run pylint
      - run: uv run mypy
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - name: Run tests
        run: uv run pytest
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPN_HOST_IP }}
          username: ${{ secrets.VPN_USER_NAME }}
          password: ${{ secrets.VPN_PASSWORD }}
          port: ${{ secrets.VPN_PORT }}
          script: | 
            cd /${{ secrets.VPN_USER_NAME }}/${{ secrets.PROJECT_PATH }}
            git checkout master
            git pull
            docker build . -t=form_wizard -f=docker/Dockerfile
            docker stop form_wizard
            docker rm form_wizard
            docker run -d --env-file=.env --name form_wizard form_wizard
            docker system prune --all --force